"""add release tables

Revision ID: 32f8344f0458
Revises: 88c5ea73457b
Create Date: 2026-02-24 02:49:00.363499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f8344f0458'
down_revision: Union[str, Sequence[str], None] = '88c5ea73457b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_version'), 'releases', ['version'], unique=True)
    op.create_table('release_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_items_component_id'), 'release_items', ['component_id'], unique=False)
    op.create_index(op.f('ix_release_items_release_id'), 'release_items', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_items_release_id'), table_name='release_items')
    op.drop_index(op.f('ix_release_items_component_id'), table_name='release_items')
    op.drop_table('release_items')
    op.drop_index(op.f('ix_releases_version'), table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
